// Code generated by cmd/genapi. DO NOT EDIT.

//go:build !ignore_autogenerated

package api

type ParseMode string

const (
	ParseModeMarkdown   ParseMode = "Markdown"
	ParseModeMarkdownV2 ParseMode = "MarkdownV2"
	ParseModeHTML       ParseMode = "HTML"
)
