name: Release

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  release:
    needs: checks
    uses: lukaszraczylo/shared-actions/.github/workflows/go-release.yaml@main
    with:
      go-version: ">=1.25"
      semver-config: ".semver.yaml"
    secrets: inherit
